# this config was migrated from renv.lock on 2025-12-01
[project]
name = "/home/gnoblet/Documents/Codeberg/AddFonts"
r_version = "4.5"

repositories = [
    { alias = "CRAN", url = "https://p3m.dev/cran/2025-11-25/bin/linux/manylinux_2_28-x86_64/4.5"}
]

dependencies = [
    "httr2",
    "usethis",
    "testthat",
    "sysfonts",
    "fs",
    "devtools",
    "roxytypes",
    "showtext",
    "ggplot2",
    "dplyr",
    "tidyr",
    "S7",
    "jsonlite",
    "pak",
    {name = "hexSticker", git = "https://github.com/GuangchuangYu/hexSticker.git",  branch = "master"},
    "svglite",
]
